# Generated by Django 5.0.6 on 2024-06-12 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_category_remove_book_discount_book_author_book_isbn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=None),
        ),
    ]
