# Generated by Django 5.0.6 on 2024-06-12 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_order_price_order_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
