# Generated by Django 5.0.6 on 2024-06-12 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_order_price_remove_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_delivered',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
